# Generated by Django 3.0rc1 on 2019-11-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=5000)),
                ('desc', models.TextField()),
            ],
        ),
    ]
